import type { Metadata } from "next";
import { Geist, Geist_Mono,Roboto,Poppins } from "next/font/google";
import "./globals.css";



const roboto=Roboto({
  subsets:['latin'],
  display:"swap"
})



export const metadata: Metadata = {
  title: "Chandra Hardwares",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        {children}
        
        </body>
    </html>
  );
}
