import type { Metadata } from "next";
import { Roboto, } from "next/font/google";
import './globals.css'
import LayoutWrapper from "./components/LayoutWrapper";
import AuthProvider from "./context/AuthContext";
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: "swap"
});


export const metadata: Metadata = {
  title: "Chandra Hardwares",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html
      lang="en"
      className={`${roboto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
           <LayoutWrapper>
            {children}
            </LayoutWrapper> 
        
        
        </AuthProvider>
       
        </body>
    </html>
  );
}
